/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 *
 * @author Bucardo
 */
import ConsultasSQL.QuerysProveedores;
import javax.swing.JOptionPane;
import Controlador.Proveedores;
import java.awt.event.KeyEvent;

public class FormEditProveedor extends javax.swing.JFrame {

    /**
     * Creates new form FormEditProveedor
     */
    public FormEditProveedor() {
        initComponents();
        setLocationRelativeTo(null);// es para colocar  la ventana en el centro de la patalla
        setResizable(false);// se usa para que la persona no puede cambiar el tamano de la ventana 
        txtId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNRepresentante = new javax.swing.JTextField();
        txtNEmpresa = new javax.swing.JTextField();
        txtfRTN = new javax.swing.JFormattedTextField();
        txfTelefono = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDireccion = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 15, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setText("Editar Representante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel2.setText("Nombre del  Representante :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel3.setText("Nombre de la Empresa :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 186, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel4.setText("RTN :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 239, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel5.setText("Teléfono :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 292, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel6.setText("Dirección :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 362, -1, -1));

        txtNRepresentante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNRepresentante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNRepresentanteKeyTyped(evt);
            }
        });
        jPanel1.add(txtNRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 115, 278, -1));

        txtNEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNEmpresaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 183, 278, -1));

        txtfRTN.setEditable(false);
        try {
            txtfRTN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfRTN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txtfRTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 233, 278, -1));

        txfTelefono.setEditable(false);
        try {
            txfTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 289, 278, -1));

        txaDireccion.setColumns(20);
        txaDireccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txaDireccion.setRows(5);
        txaDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txaDireccionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txaDireccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 362, 315, -1));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de icon/actualizado2 (1).png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 582, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de icon/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 583, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de icon/Imagen1.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        //Validacion para el nombre de representante de la empresa
        String nombreRepresent = txtNRepresentante.getText().trim();//Eliminar espacios en blanco al inicio y al final
        String emp = txtNEmpresa.getText().trim();//Eliminar espacios en blanco al inicio y al final
        String direc = txaDireccion.getText().trim();//Eliminar espacios en blanco al inicio y al final
        

         if(nombreRepresent.isEmpty()){
            JOptionPane.showMessageDialog(null, "El nombre del representante está vacío","Error al actualiazar",
                    JOptionPane.WARNING_MESSAGE);
            return; // Salir del método si el campo está vacío
        }
            if(!nombreRepresent.matches("[a-zA-ZáéíóúñÁÉÍÓÚÑ][a-zA-Z áéíóúñÁÉÍÓÚÑü]+")) {//si el nombre del departamento contiene caracteres diferentes se muestra el siguiente mensaje
            //mensaje de error 
            JOptionPane.showMessageDialog(null, "alguno de los caracteres que ingresó no es valido", "Error al actualiazar", 
                    JOptionPane.WARNING_MESSAGE);
            return;//sale del método
        }
            
        if(emp.isEmpty()){
            JOptionPane.showMessageDialog(null, "El nombre de la empresa está vacío","Error al actualiazar",
                    JOptionPane.WARNING_MESSAGE);
        return; // Salir del método si el campo está vacío
        }
       if(!emp.matches("[a-zA-ZáéíóúñÁÉÍÓÚÑ][a-zA-Z áéíóúñÁÉÍÓÚÑü]+")) {//si el nombre del departamento contiene caracteres diferentes se muestra el siguiente mensaje
            //mensaje de error 
        JOptionPane.showMessageDialog(null, "alguno de los caracteres que ingresó no es valido", "Error al actualiazar", 
                    JOptionPane.WARNING_MESSAGE);
        return;//sale del método
        }
            
       if(direc.isEmpty()){
         JOptionPane.showMessageDialog(null, "La dirreccion  está vacío","Error al actualiazar",
                    JOptionPane.WARNING_MESSAGE);
       return; // Salir del método si el campo está vacío
        }
       if(!direc.matches("[a-zA-ZáéíóúñÁÉÍÓÚÑ][a-zA-Z áéíóúñÁÉÍÓÚÑü]+")) {//si el nombre del departamento contiene caracteres diferentes se muestra el siguiente mensaje
            //mensaje de error 
        JOptionPane.showMessageDialog(null, "alguno de los caracteres que ingresó no es valido", "Error al actualiazar", 
                    JOptionPane.WARNING_MESSAGE);
        return;//sale del método
        }
     

   

        QuerysProveedores QProve = new QuerysProveedores();

        QProve.setNombre(nombreRepresent);
        QProve.setEmpresa(emp);
        QProve.setRtn(txtfRTN.getText());
        QProve.setTelefono(txfTelefono.getText());
        QProve.setDireccion(direc);
        QProve.setId(Integer.parseInt(txtId.getText()));// aqui hubieron cambios

        if (Proveedores.Editar(QProve)) {
            JOptionPane.showMessageDialog(this, "Se ha Modificado Exitosamente el Proveedor");
            Proveedores.MostrarProvedores("");
            dispose();

        } else {
            JOptionPane.showMessageDialog(this, "hay un error, consulte con el Administrador de Sistema");
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNRepresentanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNRepresentanteKeyTyped

        String V = txtNRepresentante.getText();

        if (!V.isEmpty()) {// que la primera letra sea mayuscula
            char primeraLetra = Character.toUpperCase(V.charAt(0));
            txtNRepresentante.setText(primeraLetra + V.substring(1));
        }

        if (V.startsWith(" ")) {
            txtNRepresentante.setText(V.trim());
            return;
        }
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {//&& !(evt.getKeyChar()==KeyEvent.VK_SPACE)
            // validacion desde teclado para verificar que lo esta ingresando sean letras de lo contrario nos mostrara un mensaje que diga que solo  permite letras y  incluya espacios tambien
            getToolkit().beep();
            evt.consume();

        }

        if (V.length() >= 35) {// esta validacion es para dar un maximo de logitud del nombre que se puede aceptar en la caja de texto
            evt.consume();
        }
    }//GEN-LAST:event_txtNRepresentanteKeyTyped

    private void txtNEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNEmpresaKeyTyped
        String E = txtNEmpresa.getText();

        if (!E.isEmpty()) {// que la primera letra sea mayuscula
            char primeraLetra = Character.toUpperCase(E.charAt(0));
            txtNEmpresa.setText(primeraLetra + E.substring(1));
        }

        if (E.startsWith(" ")) {
            txtNEmpresa.setText(E.trim());
            return;
        }
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {//&& !(evt.getKeyChar()==KeyEvent.VK_SPACE)
            // validacion desde teclado para verificar que lo esta ingresando sean letras de lo contrario nos mostrara un mensaje que diga que solo  permite letras y  incluya espacios tambien
            getToolkit().beep();
            evt.consume();

        }

        if (E.length() >= 35) {// esta validacion es para dar un maximo de logitud del nombre que se puede aceptar en la caja de texto
            evt.consume();
        }
    }//GEN-LAST:event_txtNEmpresaKeyTyped

    private void txaDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaDireccionKeyTyped
        // TODO add your handling code here:
       String D = txaDireccion.getText();
       
        if (!D.isEmpty()) {// que la primera letra sea mayuscula
        char primeraLetra = Character.toUpperCase(D.charAt(0));
         txaDireccion.setText(primeraLetra + D.substring(1));
        }
       if (D.startsWith(" ")) {
            txaDireccion.setText(D.trim());
            return;
        }
       
         if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {//&& !(evt.getKeyChar()==KeyEvent.VK_SPACE)
            // validacion desde teclado para verificar que lo esta ingresando sean letras de lo contrario nos mostrara un mensaje que diga que solo  permite letras y  incluya espacios tambien
            getToolkit().beep();
            evt.consume();

        }
         if (D.length() >= 35) {// esta validacion es para dar un maximo de logitud del nombre que se puede aceptar en la caja de texto
            evt.consume();
        }
        
    }//GEN-LAST:event_txaDireccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txaDireccion;
    public static javax.swing.JFormattedTextField txfTelefono;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtNEmpresa;
    public static javax.swing.JTextField txtNRepresentante;
    public static javax.swing.JFormattedTextField txtfRTN;
    // End of variables declaration//GEN-END:variables
}
