/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Josue
 */
public class MostrarProveedores extends javax.swing.JPanel {

    /**
     * Creates new form MostrarProveedores
     */
    public MostrarProveedores() {
        initComponents();
        tblMostrarProveedores.getTableHeader().setReorderingAllowed(false);
        Controlador.Proveedores.MostrarProvedores("");
        
        tblMostrarProveedores.addMouseListener(new MouseAdapter(){
        
        public void mouseClicked(MouseEvent evt){
          if (evt.getClickCount()== 2){
            int fila = tblMostrarProveedores.getSelectedRow();
            VerProveedor verProveedor = new VerProveedor(); 
         // prov.setVisible(true);
        int row = tblMostrarProveedores.getSelectedRow() ;
     //   VerProveedor.tfI.setText(tblMostrarProveedores.getValueAt(row, 0).toString());
     
        VerProveedor.Nombre.setText(tblMostrarProveedores.getValueAt(row, 1).toString());
        VerProveedor.Empresa.setText(tblMostrarProveedores.getValueAt(row, 2).toString());
        VerProveedor.Rtn.setText(tblMostrarProveedores.getValueAt(row, 3).toString());
        VerProveedor.Telefono.setText(tblMostrarProveedores.getValueAt(row, 4).toString());
        VerProveedor.Direccion.setText(tblMostrarProveedores.getValueAt(row, 5).toString());
        verProveedor.setVisible(true);
        //  } else {
         // JOptionPane.showMessageDialog(this, "no presiono dos veces");
         }
        }
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarProveedores = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        tblMostrarProveedores = new JTable(){
            public boolean isCellEditable(int row, int column){
                for(int i=0; i< tblMostrarProveedores.getRowCount(); i++){
                    if(row == i){
                        return false;
                    }
                }
                return true ;
            }
        };
        tblMostrarProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Empresa", "RTN", "Teléfono ", "Dirección"
            }
        ));
        tblMostrarProveedores.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(tblMostrarProveedores);

        btnNuevo.setText("+");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Listado de provedores");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnImprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(jLabel1)
                    .addComponent(btnEdit)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        ProveedoresStore proveedores = new ProveedoresStore();
        proveedores.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
              FormEditProveedor mostradatos = new FormEditProveedor();
              
              
        int fila = tblMostrarProveedores.getSelectedRow();  
        
        if (fila>=0){
            
        mostradatos.txtId.setText(tblMostrarProveedores.getValueAt(fila, 0).toString());   // aqui se agrego esto
        mostradatos.txtNRepresentante.setText(tblMostrarProveedores.getValueAt(fila, 1).toString());
        mostradatos.txtNEmpresa.setText(tblMostrarProveedores.getValueAt(fila, 2).toString());
        mostradatos.txtfRTN.setText(tblMostrarProveedores.getValueAt(fila, 3).toString());
        mostradatos.txfTelefono.setText(tblMostrarProveedores.getValueAt(fila, 4).toString());
        mostradatos.txaDireccion.setText(tblMostrarProveedores.getValueAt(fila, 5).toString());
       //ediFormProv.tfI.setText(tblMostrarProveedores.getValueAt(fila, 0).toString());
       mostradatos.setVisible(true);
        } else {
        JOptionPane.showMessageDialog(null,  " no hay fila");
        }

    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblMostrarProveedores;
    // End of variables declaration//GEN-END:variables
}
