/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import ConsultasSQL.QuerysDepartamentos;
import javax.swing.JOptionPane;
import Controlador.Departamentos;
import Controlador.Proveedores;

/**
 *
 * @author Andrea
 */
public class CrearDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form CrearDepartamento
     */
    public CrearDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUbicacion = new javax.swing.JTextArea();
        txtNombreDepartamento = new javax.swing.JTextField();
        txtPrefijo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel1.setText("Nombre del departamento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 116, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(249, 253, 250));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 150, 61));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel2.setText("Prefijo ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel3.setText("Ubicación");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 259, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel4.setText("Nuevo departamento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 34, -1, -1));

        txtUbicacion.setColumns(20);
        txtUbicacion.setRows(5);
        txtUbicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUbicacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtUbicacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 120));

        txtNombreDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNombreDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDepartamentoActionPerformed(evt);
            }
        });
        txtNombreDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreDepartamentoKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 116, 234, -1));

        txtPrefijo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPrefijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrefijoActionPerformed(evt);
            }
        });
        txtPrefijo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrefijoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrefijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 234, -1));

        btnCancelar.setBackground(new java.awt.Color(249, 253, 250));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 150, 61));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alcaldiaDepto.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       //VALIDACIONES
       //Validación para el nombre del departamento
       String nombreDepartamento = txtNombreDepartamento.getText();
        if(nombreDepartamento.isEmpty()){
            JOptionPane.showMessageDialog(null, "El nombre del departamento está vacío","Error al guardar",
                    JOptionPane.WARNING_MESSAGE);
            return; // Salir del método si el campo está vacío
        }
        if(!nombreDepartamento.matches("[a-zA-ZáéíóúñÁÉÍÓÚÑ][a-zA-Z áéíóúñÁÉÍÓÚÑ]+")) {//si el nombre del departamento contiene caracteres diferentes se muestra el siguiente mensaje
            //mensaje de error 
            JOptionPane.showMessageDialog(null, "alguno de los caracteres que ingresó no es valido", "Errror al guardar", 
                    JOptionPane.WARNING_MESSAGE);
            return;//sale del método
        }
        
        //Validación para el prefijo del departamento
        String prefijo = txtPrefijo.getText().trim();
        if(prefijo.isEmpty()){//si el prefijo está vacío
            //se muestra el mensaje de error
            JOptionPane.showMessageDialog(null, "El prefijo del departamento está vacío","Error al guardar",
                    JOptionPane.WARNING_MESSAGE);
            return;//sale del método
        }
        
        //Validación para la ubicación
        String ubicacion = txtUbicacion.getText();
         if(ubicacion.isEmpty()){
             JOptionPane.showMessageDialog(null, "La ubicación del departamento está vacía","Error al guardar",
                    JOptionPane.WARNING_MESSAGE);
            return;//sale del método
         }     
         
         if(!ubicacion.matches("[a-zA-ZáéíóúñÁÉÍÓÚÑ][a-zA-Z0-9 áéíóúñÁÉÍÓÚÑü.:;]+")){
             JOptionPane.showMessageDialog(null, "alguno de los caracteres que ingresó no es valido", "Error al guardar", 
                    JOptionPane.WARNING_MESSAGE);
            return;//sale del método
         }
         
         
         //crear una instancia de querysDepartamento
         QuerysDepartamentos querys = new QuerysDepartamentos();
         querys.setNombreDepartamento(nombreDepartamento);
         querys.setPrefijo(prefijo);
         querys.setUbicacion(ubicacion);
         
         if (Departamentos.Guardar(querys)){
             JOptionPane.showMessageDialog(this, "Nuevo departamento ingresado exitosamente");
                //Departamentos.MostrarDepartamentos("");
                dispose();
         }else {
                JOptionPane.showMessageDialog(null, "Algo falló, consulte con el administrador de sistema", "Error al guardar", 
                    JOptionPane.OK_OPTION);
         }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDepartamentoActionPerformed

    private void txtPrefijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrefijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrefijoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreDepartamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDepartamentoKeyTyped
       //si el nombre del departamento tiene mas de 45 caracteres
        if(txtNombreDepartamento.getText().length() >= 45){
        evt.consume();// no permite seguir escribiendo en el campo
        }
    }//GEN-LAST:event_txtNombreDepartamentoKeyTyped

    private void txtPrefijoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrefijoKeyTyped
        
        //validación para que en el prefijo solo acepte letras 
        char validar = evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
        
        //validación para que no acepte mas de 5 letras
        if(txtPrefijo.getText().length() >= 5){//cuando el prefijo llegue a las 5 letras
        evt.consume();//no permite que sigan escribiendo en el campo
        }
    }//GEN-LAST:event_txtPrefijoKeyTyped

    private void txtUbicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUbicacionKeyTyped
        if(txtUbicacion.getText().length() >= 50){//si la ubicación es mayor a 50 caracteres 
        evt.consume();//no permite que sigan escribiendo en el campo
        }
    }//GEN-LAST:event_txtUbicacionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNombreDepartamento;
    private javax.swing.JTextField txtPrefijo;
    private javax.swing.JTextArea txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
