/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import ConsultasSQL.QuerysDepartamentos;
import javax.swing.JOptionPane;
import Controlador.Departamentos;
import java.awt.event.KeyEvent;

/**
 *
 * @author Bucardo
 */
public class EditDepto extends javax.swing.JFrame {

    /**
     * Creates new form EditDepto
     */
    public EditDepto() {
        //initComponents();
       //  setLocationRelativeTo(null);// es para colocar  la ventana en el centro de la patalla
       // setResizable(false);// se usa para que la persona no puede cambiar el tamano de la ventana 
       
       initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        txtId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtNombreDepartamento = new javax.swing.JTextField();
        txtPrefijo = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaUbicacion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setText("editando departamento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel2.setText("Nombre de departamento :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 108, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel3.setText("prefijo :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel4.setText("ubicación :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        btnactualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnactualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnactualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Editar.png"))); // NOI18N
        btnactualizar.setText("actualizar ");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 374, -1, -1));

        btncancelar.setBackground(new java.awt.Color(255, 255, 255));
        btncancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(0, 0, 0));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelarr.png"))); // NOI18N
        btncancelar.setText("cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 375, 120, 50));

        txtNombreDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNombreDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreDepartamentoKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 108, 280, -1));

        txtPrefijo.setEditable(false);
        txtPrefijo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txtPrefijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 280, -1));

        txtId.setEditable(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 20, -1, -1));

        txaUbicacion.setColumns(20);
        txaUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txaUbicacion.setRows(5);
        txaUbicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txaUbicacionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txaUbicacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 210, 300, 125));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alcaldiaDepto.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 520, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDepartamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDepartamentoKeyTyped
        // TODO add your handling code here:
          String n = txtNombreDepartamento.getText();
       
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {//&& !(evt.getKeyChar()==KeyEvent.VK_SPACE)
            // validacion desde teclado para verificar que lo esta ingresando sean letras de lo contrario nos mostrara un mensaje que diga que solo  permite letras y  incluya espacios tambien
            getToolkit().beep();
            evt.consume();

        }
        
           if (n.startsWith(" ")) {
            txtNombreDepartamento.setText(n.trim());
            return;
        }

        if (n.length() >= 30) {// esta validacion es para dar un maximo de logitud del nombre que se puede aceptar en la caja de texto
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreDepartamentoKeyTyped

    private void txaUbicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaUbicacionKeyTyped
        // TODO add your handling code here:
        String U = txaUbicacion.getText();
       
       // if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)|| evt.getKeyChar() == ',' || evt.getKeyChar() == '.' ) {
           
        //    getToolkit().beep();
        //    evt.consume();

      //  }
        
           if (U.startsWith(" ")) {
            txaUbicacion.setText(U.trim());
            return;
        }

        if (U.length() >= 30) {// esta validacion es para dar un maximo de logitud del nombre que se puede aceptar en la caja de texto
            evt.consume();
        }
        
    //    if (!txaUbicacion.getText().matches("[a-zA-Z,.\\s]+")) {
            
      //      evt.consume();
       //  }   
         char c = evt.getKeyChar();// esta validacion esta perfecta
       if (!Character.isLetter(c) && !Character.isWhitespace(c) && c != ',' && c != '.') {
           getToolkit().beep();
            evt.consume();
        }

        
    }//GEN-LAST:event_txaUbicacionKeyTyped

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
          String nombre = txtNombreDepartamento.getText().trim();//Eliminar espacios en blanco al inicio y al final
          String ubic = txaUbicacion.getText().trim();//Eliminar espacios en blanco al inicio y al final
        

         if(nombre.isEmpty()){
             
             JOptionPane.showMessageDialog(this, "el nombre de  departamento  está vacío");
          
            return; // Salir del método si el campo está vacío
        }
            if(!nombre.matches("[a-zA-ZáéíóúñÁÉÍÓÚÑ][a-zA-Z áéíóúñÁÉÍÓÚÑü]+")) {//si el nombre del departamento contiene caracteres diferentes se muestra el siguiente mensaje
            //mensaje de error 
            
            JOptionPane.showMessageDialog(this, "alguno de los caracteres que ingresó no es valido");
            return;//sale del método
        }
       
        

         if(ubic.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "la ubicación  está vacío");
            return; // Salir del método si el campo está vacío
        }
            if(!ubic.matches("[a-zA-ZáéíóúñÁÉÍÓÚÑ,.\\s][a-zA-Z áéíóúñÁÉÍÓÚÑü,.\\s]+")) {//si el nombre del departamento contiene caracteres diferentes se muestra el siguiente mensaje
            //mensaje de error 
             JOptionPane.showMessageDialog(this, "alguno de los caracteres que ingresó no es valido");
         
            
            return;//sale del método
        }
            
          QuerysDepartamentos QProve = new QuerysDepartamentos();

          QProve.setNombreDepartamento(nombre);
          QProve.setPrefijo(txtPrefijo.getText());
          QProve.setUbicacion(ubic);
          QProve.setId(Integer.parseInt(txtId.getText()));
         if (Departamentos.Editar(QProve)) {
         JOptionPane.showMessageDialog(this, "Se ha Modificado Exitosamente el departamento");
         Departamentos.MostrarDepartamentos("");
         dispose();

        } else {
                JOptionPane.showMessageDialog(null, "hay un error, consulte con el Administrador de Sistema", "Error de base de datos", 
                    JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDepto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txaUbicacion;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtNombreDepartamento;
    public static javax.swing.JTextField txtPrefijo;
    // End of variables declaration//GEN-END:variables
}
