/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import ConsultasSQL.QuerysEmpleados;
import javax.swing.JOptionPane;
import Controlador.Empleados;
import java.awt.event.KeyEvent;


/**
 *
 * @author Josue
 */
public class EmpleadosStore extends javax.swing.JFrame {

    /**
     * Creates new form Proveedores
     */
    public EmpleadosStore() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fmt_identidad = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        fmt_telefono = new javax.swing.JFormattedTextField();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 130, -1));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 240, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 138, -1));

        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 240, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Identidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 138, -1));

        try {
            fmt_identidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmt_identidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmt_identidadActionPerformed(evt);
            }
        });
        jPanel1.add(fmt_identidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 240, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Teléfono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 138, -1));

        try {
            fmt_telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmt_telefonoActionPerformed(evt);
            }
        });
        fmt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fmt_telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(fmt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 240, -1));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 350, -1, -1));

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 351, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ingresar un nuevo empleado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 260, 32));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alcaldiaDepto.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, -1, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fmt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmt_telefonoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
         String nomEmp = txt_nombre.getText().trim(); // Eliminar espacios en blanco al inicio y al final
        if (nomEmp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del empleado no puede estar vacio");
            return; // Salir del método si el campo está vacío
        }
        if (!nomEmp.matches("[a-zA-Záéíóúñ][a-zA-Z áéíóúñ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre del empleado solo puede contener letras");
            return; // Salir del método si el nombre contiene caracteres no válidos
        }
        
         String apeEmp = txt_apellido.getText().trim(); // Eliminar espacios en blanco al inicio y al final
        if (apeEmp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El apellido del empleado no puede estar vacio");
            return; // Salir del método si el campo está vacío
        }
        if (!apeEmp.matches("[a-zA-Záéíóúñ][a-zA-Z áéíóúñ]+")) {
            JOptionPane.showMessageDialog(this, "El apellido del empleado solo puede contener letras");
            return; // Salir del método si el nombre contiene caracteres no válidos
        }
       
        String ideEmp = fmt_identidad.getText().trim(); // Eliminar espacios en blanco al inicio y al final
        if (ideEmp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "el numero de identidad está vacío");
            return; // Salir del método si el campo está vacío
        }
        /* if (!rtnPro.matches("[0-9][-0-9]+")) {
            JOptionPane.showMessageDialog(this, "El rtn debe contener 14 numeros");
            return; // Salir del método si el nombre contiene caracteres no válidos
        }*/
        if(ideEmp.equals("0000-0000-00000")){
                JOptionPane.showMessageDialog(this,"La identidad no puede ser cero");
                        return;
            }
        
        
        String telEmp = fmt_telefono.getText().trim(); // Eliminar espacios en blanco al inicio y al final
        if (telEmp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de telefono está vacío");
            return; // Salir del método si el campo está vacío
        }
       /*  if (!telProv.matches("[0-9][-0-9]+")) {
            JOptionPane.showMessageDialog(this, "El telefono debe contener 8 numeros");
            return; // Salir del método si el nombre contiene caracteres no válidos
        }*/
       
       if (telEmp.equals("0000-0000")) {
            JOptionPane.showMessageDialog(this, "El teléfono no debe ser cero");
             return; // Salir del método si el teléfono no es válido
         }
              
           
            // Crear una instancia de QuerysProductos
            QuerysEmpleados querys = new QuerysEmpleados();
            querys.setNombre(nomEmp);
            querys.setApellido(apeEmp);
            querys.setIdentidad(ideEmp);
            querys.setTelefono(telEmp);
            

            // Llamar al método Guardar de la clase Productos para guardar los datos
            if (Empleados.Guardar(querys)) {
                JOptionPane.showMessageDialog(this, "Nuevo Empleado Ingresado Exitosamente");
                
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "El Telefono o la identidad ya estan ingresados");
            }
    

    }//GEN-LAST:event_btn_guardarActionPerformed


    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed



    private void fmt_rtnKeyTyped(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
    }                                
    // TODO add your handling code here:

    private void fmt_rtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmt_rtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmt_rtnKeyPressed
   



    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
          String Valor =txt_nombre.getText();
        
        if (!Valor.isEmpty()) {// que la primera letra sea mayuscula
        char primeraLetra = Character.toUpperCase(Valor.charAt(0));
         txt_nombre.setText(primeraLetra + Valor.substring(1));
        }
         
        
       if (Valor.startsWith(" ")){
             JOptionPane.showMessageDialog(this, "el nombre no puede iniciar con espacios ");// no puede iniciar con  espacios
          txt_nombre.setText(Valor);
          return;
        }
       if(Valor.length()>=40){
     //  JOptionPane.showMessageDialog(this, "el nombre no puede contener mas de 40 letras");
     evt.consume();
       }

    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
      String Valor =txt_apellido.getText();
        
        if (!Valor.isEmpty()) {// que la primera letra sea mayuscula
        char primeraLetra = Character.toUpperCase(Valor.charAt(0));
         txt_apellido.setText(primeraLetra + Valor.substring(1));
        }
               
       if (Valor.startsWith(" ")){
             JOptionPane.showMessageDialog(this, "el nombre de empresa no puede iniciar con espacios ");// no puede iniciar con  espacios
          txt_apellido.setText(Valor);
          return;
        }
       if(Valor.length()>=40){
       JOptionPane.showMessageDialog(this, "el nombre de empresa no puede contener mas de 40 letras");}
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void fmt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fmt_telefonoKeyTyped
        String Valor = fmt_telefono.getText();
        
        if(fmt_telefono.getText().equals("0000-0000")){
            JOptionPane.showMessageDialog(this, "No se acepta el telefono 0000-0000");
        }
    }//GEN-LAST:event_fmt_telefonoKeyTyped

    private void fmt_identidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmt_identidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmt_identidadActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JFormattedTextField fmt_identidad;
    private javax.swing.JFormattedTextField fmt_telefono;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
