/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import javax.swing.table.DefaultTableModel;
import Conexion.Conexion;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JTextField;
import static Vistas.IngresarCompra.proveedorSeleccionadoNombre;

public class MostrarCompras extends javax.swing.JPanel {
    public MostrarCompras() {
        initComponents();
        tblMostrarCompras.getTableHeader().setReorderingAllowed(false);
        Controlador.Compras.MostrarCompras("");
        
        
        tblMostrarCompras.addMouseListener(new MouseAdapter(){
          
            public void mouseClicked(MouseEvent e){
                if (e.getClickCount() == 2){
                    int fila = tblMostrarCompras.getSelectedRow();
                    VerCompras vercompras = new VerCompras();
                    vercompras.nFact.setText(tblMostrarCompras.getValueAt(fila, 0).toString());
                    vercompras.nRtn.setText(tblMostrarCompras.getValueAt(fila, 1).toString());
                    vercompras.nCai.setText(tblMostrarCompras.getValueAt(fila, 2).toString());
                    vercompras.ntCompra.setText(tblMostrarCompras.getValueAt(fila, 3).toString());
                    vercompras.nProv.setText(proveedorSeleccionadoNombre);
                    vercompras.nFecha.setText(tblMostrarCompras.getValueAt(fila, 4).toString());
                    vercompras.ntotFact.setText("Lps."+tblMostrarCompras.getValueAt(fila, 5).toString());
            
                    vercompras.setVisible(true);
                    vercompras.setLocationRelativeTo(null);
                }
            }
        });
        
    }
    
    
    public void filtrarDatos(String valor){
        String[] titulos = {"<html><b>Num.Factura</b></html>","<html><b>RTN</b></html>","<html><b>CAI</b></html>",
            "<html><b>Tipo de compra</b></html>","<html><b>Fecha</b></html>","<html><b>Total</b></html>"};
        String[] registros = new String[7];
        
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "select * from compras WHERE numeroDocumento like '%"+valor+"%' or "
                + "rtn like '%"+valor+"%' or cai like '%"+valor+"%' or tipoCompra like '%"+valor+"%'"
                + "or fecha like '%"+valor+"%'";
        
        
        
        try {
            Statement st=(Statement) Conexion.getConection().createStatement();
            ResultSet rs= st.executeQuery(SQL);
            
            while(rs.next()){
                registros[0]=rs.getString("numeroDocumento");
                registros[1]=rs.getString("rtn");
                registros[2]=rs.getString("cai");
                registros[3]=rs.getString("tipoCompra");
                //registros[4]=rs.getString("fk_proveedor");
                registros[4]=rs.getString("fecha");
                registros[5]=rs.getString("total");
                
                modelo.addRow(registros);
                
            }
            
            MostrarCompras.tblMostrarCompras.setModel(modelo);
            
        } catch (Exception e) {
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarCompras = new javax.swing.JTable();
        AgregarCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CuadroBusqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        tblMostrarCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        //hacer que la tabla no sea editabe
        tblMostrarCompras.setFocusable(false);
        tblMostrarCompras = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblMostrarCompras.setToolTipText("");
        tblMostrarCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblMostrarComprasKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblMostrarCompras);
        if (tblMostrarCompras.getColumnModel().getColumnCount() > 0) {
            tblMostrarCompras.getColumnModel().getColumn(6).setResizable(false);
        }

        AgregarCompra.setBackground(new java.awt.Color(253, 253, 253));
        AgregarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        AgregarCompra.setText("Nuevo");
        AgregarCompra.setBorder(null);
        AgregarCompra.setOpaque(true);
        AgregarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarCompraMouseExited(evt);
            }
        });
        AgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCompraActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Listado de  facturas de Compras");

        CuadroBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CuadroBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CuadroBusquedaFocusLost(evt);
            }
        });
        CuadroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroBusquedaActionPerformed(evt);
            }
        });
        CuadroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CuadroBusquedaKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo Listados.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CuadroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AgregarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CuadroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AgregarCompra)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCompraActionPerformed
        // TODO add your handling code here:
        IngresarCompra compras = new IngresarCompra();
        compras.setVisible(true);
        compras.setLocationRelativeTo(null);
    }//GEN-LAST:event_AgregarCompraActionPerformed

    private void CuadroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroBusquedaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CuadroBusquedaActionPerformed

    private void CuadroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CuadroBusquedaKeyReleased
        // TODO add your handling code here:
        //codigo para el cuadro de busqueda en el JTextfield
        filtrarDatos(CuadroBusqueda.getText());
        
    }//GEN-LAST:event_CuadroBusquedaKeyReleased

    private void CuadroBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CuadroBusquedaFocusGained
        // TODO add your handling code here:
        //placeholder para notificar como realizar la busqueda
        JTextField textField = (JTextField) evt.getSource();
        String placeholder = "Busqueda por todos los campos excepto total";

        if (textField.getText().equals(placeholder)) {
            textField.setText("");
            textField.setForeground(Color.BLACK); // Establece el color de fuente adecuado
        }
    }//GEN-LAST:event_CuadroBusquedaFocusGained

    private void CuadroBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CuadroBusquedaFocusLost
        // TODO add your handling code here:
        //placeholder para notificar como realizar la busqueda
          JTextField textField = (JTextField) evt.getSource();
          String placeholder = "Busqueda por todos los campos excepto total";

          if (textField.getText().isEmpty()) {
            textField.setText(placeholder);
            textField.setForeground(Color.GRAY); // Establece el color de fuente del placeholder
          }
    }//GEN-LAST:event_CuadroBusquedaFocusLost

    private void AgregarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCompraMouseEntered
        // TODO add your handling code here:
        //cambiar el color del boton cuando el mouse entra
        //AgregarCompra.setBackground(new Color(42, 126, 126));
        
    }//GEN-LAST:event_AgregarCompraMouseEntered

    private void AgregarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCompraMouseExited
        // TODO add your handling code here:
        //cambiar el color cuando el mouse salga del boton
        //AgregarCompra.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_AgregarCompraMouseExited

    private void tblMostrarComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMostrarComprasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMostrarComprasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCompra;
    private javax.swing.JTextField CuadroBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblMostrarCompras;
    // End of variables declaration//GEN-END:variables

}
