/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import static Vistas.MostrarTerreno.totalPages;
import com.mysql.cj.x.protobuf.MysqlxExpr;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.text.PlainDocument;
import org.jdesktop.swingx.prompt.PromptSupport;
import org.tinygroup.placeholder.PlaceholderMainClass;

/**
 *
 * @author Bucardo
 */
public class MostrarTerreno extends javax.swing.JPanel {

    private int paginaActual = 1;
    public static int totalPages = Controlador.Terrenos.NumeroPages();
    /**
     * Creates new form MostrarTerreno
     */
    public MostrarTerreno() {
        initComponents();
        tblMostrarTerrenos.getTableHeader().setReorderingAllowed(false);
        Controlador.Terrenos.MostrarTerreno("", paginaActual, totalPages);
        
         PromptSupport.setPrompt("Buscar por terreno ,código y ubicación", txtbusqueda);// es como placeholder 
         
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarTerrenos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        previo = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        seguimiento = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMostrarTerrenos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Código", "Terreno Municipales", "Cantidad", "Responsable", "Ubicación", "Cargo", "Valor", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMostrarTerrenos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 830, 290));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setText("Listado de Terrenos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        imprimir.setBackground(new java.awt.Color(255, 255, 248));
        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.png"))); // NOI18N
        imprimir.setText("Imprimir");
        jPanel1.add(imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, -1, -1));

        nuevo.setBackground(new java.awt.Color(255, 255, 248));
        nuevo.setForeground(new java.awt.Color(51, 51, 51));
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo2.png"))); // NOI18N
        nuevo.setText("Nuevo");
        jPanel1.add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, -1, -1));

        editar.setBackground(new java.awt.Color(255, 255, 248));
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar2.png"))); // NOI18N
        editar.setText("Editar");
        jPanel1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 120, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo Listados.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 80));

        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 230, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        jLabel4.setText("Buscar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));

        previo.setBackground(new java.awt.Color(253, 253, 252));
        previo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_atras.png"))); // NOI18N
        previo.setContentAreaFilled(false);
        previo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previoActionPerformed(evt);
            }
        });
        jPanel1.add(previo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 40, 40));

        siguiente.setBackground(new java.awt.Color(253, 253, 252));
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_delante.png"))); // NOI18N
        siguiente.setContentAreaFilled(false);
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 40, 40));

        seguimiento.setText("Pagina");
        jPanel1.add(seguimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyReleased
        // TODO add your handling code here:
         String textoBusqueda = txtbusqueda.getText();
        Controlador.Terrenos.MostrarTerreno(textoBusqueda, paginaActual, totalPages);
    }//GEN-LAST:event_txtbusquedaKeyReleased

    private void previoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previoActionPerformed
        // TODO add your handling code here:
        if (paginaActual > 1 ){
           paginaActual--;
           Controlador.Terrenos.MostrarTerreno(txtbusqueda.getText(), paginaActual, totalPages);
//         
        }
        
    }//GEN-LAST:event_previoActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        if (paginaActual > totalPages ){
           paginaActual++;
           Controlador.Terrenos.MostrarTerreno(txtbusqueda.getText(), paginaActual, totalPages);
//         
        }
    }//GEN-LAST:event_siguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editar;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    public static javax.swing.JButton previo;
    public static javax.swing.JLabel seguimiento;
    public static javax.swing.JButton siguiente;
    public static javax.swing.JTable tblMostrarTerrenos;
    public static javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
